### ISSUE TITLE
Transparent rgb pixel when all 3 values of original pixels are below browse_type min and no-data is set to 0

### ISSUE THREAD

**Issue by lubojr** [EOxServer/eoxserver#493]
Problem: When all three original band values are below their respective browse_type minimum stretch values, final pixel is made transparent when no-data is set for the bands to 0. 

Reference: 
https://gitlab.eox.at/esa/prism/vs/-/issues/107

stretch with dim_range 50 255, 50 255, 50 255
![image](https://user-images.githubusercontent.com/19269667/134337575-16fbeb4b-e579-421e-a98c-ef2c23a4e6b1.png)

stretch with dim_range 45 255, 45 255, 45 255
![image](https://user-images.githubusercontent.com/19269667/134337646-e57fda7e-f520-492f-94f8-7336299b0386.png)

Maybe this piece of code is where it takes place https://github.com/EOxServer/eoxserver/blob/2b85259c8f1d56358388dbdaabe80e93fd992364/eoxserver/render/mapserver/factories.py#L864

**Comment by jankovicgd** [comment]
found a workaround for some usecases.

With byte data it is possible to define something like:
```yaml
            TRUE_COLOR:
              asset: multispectral
              red:
                nodata: null
                expression: red
                range:
                  - -1
                  - 255
              green:
                nodata: null
                expression: green
                range:
                  - -1
                  - 255
              blue:
                nodata: null
                expression: blue
                range:
                  - -1 
                  - 255
              alpha:
                expression: a
                range:
                  - 0
                  - 255
```
If the lower bound is 0 it is excluded as nodata and made transparent even if 0 is not actually a nodata value. Setting -1 as the lower bound includes 0 as data, meaning at some point it is exclusive at the lower bound (maybe also upper)
